modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
[[mods]]
modId="itemstitchingfix"
version="1.0"
displayName="Item Stitching Fix"
logoFile="logo.png"
credits="Mod by Cy4, Original Fabric Mod by PepperCode1"
description='''
A mod that fixes the small gap between the sides of generated item models!
The mod comes with a config where you can configure between various algorithms.
'''

[[dependencies.itemstitchingfix]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.itemstitchingfix]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="BOTH"
