on:
  issue_comment:
    types: [created]
  issues:
    types: [opened]

jobs:
  carbonate:
    runs-on: ubuntu-latest
    name: Generate Carbonate Image
    steps:
      - name: Checkout
        uses: actions/checkout@v2
       
      - name: Clone cabonate
        run: |
          git clone https://github.com/callmekatootie/carbonate.git --recursive ./crab
        
      - name: Generate beautiful images for code blocks present in issues
        uses: ./crab
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          imgur-client-id: ${{ secrets.IMGUR_CLIENT_ID }}
